package dependencies

internal object Versions {

    const val KOTLIN = "1.3.41"
    const val SUPPORT_LIBRARY = "1.0.0"
    const val APP_COMPAT = "1.0.2"
    const val LIFECYCLE = "2.0.0"
    const val ARCH = "1.1.1"
    const val PAGING = "1.0.1"
    const val CONSTRAINT_LAYOUT = "1.1.3"
    const val OKHTTP = "3.8.1"
    const val RETROFIT = "2.3.0"
    const val JUNIT = "4.12"
    const val REQUEST_MATCHER = "2.2.0"
    const val MOCKWEB_SERVER = "3.8.1"
    const val MOCKITO = "2.27.0"
    const val MOCKITO_KOTLIN = "2.1.0"
    const val ESPRESSO = "3.1.1"
    const val TEST_RUNNER = "1.1.1"
    const val ROBOLECTRIC = "4.2.1"
    const val ROBOLECTRIC_SHAOW = "3.3.2"
    const val ANDROIDX_TEST = "1.0.0"
    const val ROOM = "2.0.0"
    const val CORE_TEST = "1.1.0"
    const val CORE_TEST_ARCH = "2.0.1"
    const val CORE_ARCH = "2.0.1"
    const val GSON = "2.8.5"
    const val TIMBER = "4.7.1"
    const val NAVIGATION = "2.0.0"
    const val NAVIGATION_SAFE_ARGS = "1.0.0"
    const val GRADLE = "3.4.2"
    const val CIRCLE_IMAGE = "3.0.0"
}
